/**
 * Pixelmator Pro — HDR + advanced export functions unit tests.
 *
 * Tests the AppleScript generated by each export function.
 * No document.js module mock here — tests call the real functions and inspect
 * the script passed to the (mocked) runAppleScript.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";

vi.mock("../src/runners/applescript.js", () => ({
  runAppleScript: vi.fn().mockResolvedValue(""),
  escapeAppleScriptString: (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"'),
}));

vi.mock("../src/config.js", () => ({
  loadConfig: () => ({ pixelmatorBundleId: "com.apple.pixelmator" }),
}));

import { runAppleScript } from "../src/runners/applescript.js";
import {
  HDR_FORMATS, VIDEO_FORMATS, ANIMATED_FORMATS, WEB_FORMATS,
  exportHdr, exportVideo, exportAnimated, exportForWeb,
} from "../src/apps/pixelmator/document.js";

beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(runAppleScript).mockResolvedValue("");
});

describe("HDR_FORMATS", () => {
  it("has 4 HDR formats", () => {
    expect(HDR_FORMATS).toHaveLength(4);
    expect(HDR_FORMATS).toContain("HDR JPEG");
    expect(HDR_FORMATS).toContain("HDR HEIC");
    expect(HDR_FORMATS).toContain("HDR AVIF");
    expect(HDR_FORMATS).toContain("HDR PNG");
  });
});

describe("VIDEO_FORMATS", () => {
  it("includes MP4 and QuickTime Movie", () => {
    expect(VIDEO_FORMATS).toContain("MP4");
    expect(VIDEO_FORMATS).toContain("QuickTime Movie");
  });
});

describe("ANIMATED_FORMATS", () => {
  it("includes Animated GIF and Animated PNG", () => {
    expect(ANIMATED_FORMATS).toContain("Animated GIF");
    expect(ANIMATED_FORMATS).toContain("Animated PNG");
  });
});

describe("WEB_FORMATS", () => {
  it("has 5 web formats", () => {
    expect(WEB_FORMATS).toHaveLength(5);
    expect(WEB_FORMATS).toContain("PNG");
    expect(WEB_FORMATS).toContain("WebP");
    expect(WEB_FORMATS).toContain("SVG");
  });
});

describe("exportHdr", () => {
  it("sets display hdr content before export", async () => {
    await exportHdr({ documentName: "MyDoc", outputPath: "/tmp/out.heic", format: "HDR HEIC" });
    const script = vi.mocked(runAppleScript).mock.calls[0][0] as string;
    expect(script).toContain("display hdr content");
    expect(script).toContain("HDR HEIC");
    expect(script).toContain("/tmp/out.heic");
  });

  it("includes compression factor when supplied", async () => {
    await exportHdr({ documentName: "Doc", outputPath: "/tmp/o.jpg", format: "HDR JPEG", compressionFactor: 85 });
    const script = vi.mocked(runAppleScript).mock.calls[0][0] as string;
    expect(script).toContain("compression factor:85");
  });

  it("includes color profile when supplied", async () => {
    await exportHdr({ documentName: "Doc", outputPath: "/tmp/o.heic", format: "HDR HEIC", colorProfile: "Display P3" });
    const script = vi.mocked(runAppleScript).mock.calls[0][0] as string;
    expect(script).toContain("Display P3");
  });
});

describe("exportVideo", () => {
  it("generates export as MP4 script", async () => {
    await exportVideo({ documentName: "Doc", outputPath: "/tmp/v.mp4", format: "MP4" });
    const script = vi.mocked(runAppleScript).mock.calls[0][0] as string;
    expect(script).toContain("MP4");
    expect(script).toContain("/tmp/v.mp4");
  });

  it("includes frame rate when supplied", async () => {
    await exportVideo({ documentName: "Doc", outputPath: "/tmp/v.mp4", format: "MP4", frameRate: 30 });
    const script = vi.mocked(runAppleScript).mock.calls[0][0] as string;
    expect(script).toContain("frame rate:30");
  });
});

describe("exportAnimated", () => {
  it("generates export as Animated GIF script", async () => {
    await exportAnimated({ documentName: "Doc", outputPath: "/tmp/a.gif", format: "Animated GIF" });
    const script = vi.mocked(runAppleScript).mock.calls[0][0] as string;
    expect(script).toContain("Animated GIF");
  });
});

describe("exportForWeb", () => {
  it("uses export for web command", async () => {
    await exportForWeb({ documentName: "Doc", outputPath: "/tmp/w.webp", format: "WebP" });
    const script = vi.mocked(runAppleScript).mock.calls[0][0] as string;
    expect(script).toContain("export for web");
    expect(script).toContain("WebP");
  });

  it("includes scale and convert to sRGB options", async () => {
    await exportForWeb({ documentName: "Doc", outputPath: "/tmp/w.png", format: "PNG", scale: 2, convertToSRGB: true });
    const script = vi.mocked(runAppleScript).mock.calls[0][0] as string;
    expect(script).toContain("scale:2");
    expect(script).toContain("convert to sRGB:true");
  });
});
